#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     ClawStop,       sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     MotorLF,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     MotorRF,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     ClawLift,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     FlagT,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     MotorRB,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     MotorLB,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S3_C1_1,     Hook,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     NO_MOTOR,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    Out,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    In,                   tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    Belt,                 tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

#define buttonX   0x01   		//[Btn X]
#define buttonA   0x02   		//[Btn A]
#define buttonB   0x04   		//[Btn B]
#define buttonY   0x08   		//[Btn Y]
#define buttonLS   0x10   	//[Btn LB]
#define buttonRS   0x20   	//[Btn RB]
#define buttonLT   0x40   	//[Btn LT]
#define buttonRT   0x80   	//[Btn RT]
#define buttonBACK   0x100	//[Btn Back]
#define buttonSTART 0x200		//[Btn Start]

const bool bLogarithmicScale = true;
const bool kMaximumPowerLevel = 100;  // Adjust to set max power level to be used.

int scaleLog(int &nJoy1, int nMaxValue = kMaximumPowerLevel)
{
	// This function scales the joystick settings to the appropriate range for
	// controlling a NXT motor.
	//
	// Joystick values range from -128 to +127.
	// Speed/power settings for NXT motors range from -100 to +100
	//
	// The physical range of motion of a joystick is quite small and it is sometimes
	// hard to control slow speeds. So another capability of this program to apply
	// a "logarithmic" scale to the joystick settings. Our scale is not exactly a logarithmic.
	// it runs smaller numbers untill about half speed then increases quickly.
	static const int nLogScale[33] =
	{
		  0,   0,   0,	 0,		0,
		  1,	 2,   4,   5,		7,
		 	9,  11,  13,  15,	 18,
		 21,  24,	 27,  31,	 34,
		 38,	42,	 46,	51,	 55,
		 60,	65,	 70,	75,	 81,
		 87,	93,	 99,

		 };

	int nScaled;

	nScaled = nJoy1;
	if (bLogarithmicScale)
	{
	  nScaled /= 4;
	  if (nScaled >= 0)
	    nScaled = nLogScale[nScaled];
	  else
	    nScaled = - nLogScale[ - nScaled];
  }
	nScaled *= nMaxValue;
	nScaled /= 100;
  return nScaled;
}



// This is our drive function we give it variables to turn the motors correctly
void Omni(int x, int y, int rotate) {

	motor[MotorLF] = -scaleLog(x)-scaleLog(y)+scaleLog(rotate);
	motor[MotorRF] = -scaleLog(x)+scaleLog(y)+scaleLog(rotate);
	motor[MotorLB] = scaleLog(x)-scaleLog(y)+scaleLog(rotate);
	motor[MotorRB] = scaleLog(x)+scaleLog(y)+scaleLog(rotate);

}

task main()
{
//	int tmlatch=nPgmTime;

  while (true)
  {
    getJoystickSettings(joystick);  // The joystick global is defined in joystick.c

		Omni(joystick.joy1_x1, joystick.joy1_y1, -joystick.joy1_x2);

	if (joystick.joy1_Buttons & buttonA) {										// Rotate Flag
 			motor[FlagT] = 100;

		}

 		else if (joystick.joy1_Buttons & buttonY) {								// Rotate Flag
 			motor[FlagT] = -100;
			wait1Msec(5);

		}


		else
	{
		motor[FlagT]=0;
}
 						if (joystick.joy2_Buttons & buttonRS)    //lift Claw in air
    {
      motor[ClawLift] = 90;
      wait1Msec(1);
    }

    else if ((joystick.joy2_Buttons & buttonRT) && (!SensorValue[ClawStop]))		//lower Claw down
    {
      motor[ClawLift] = -25;
     wait1Msec(1);
    }

    //else if ((joystick.joy2_Buttons & buttonRT) && SensorValue[ClawStop]){
    //	if ((nPgmTime-tmlatch)>500){
    //		PlaySound(soundBeepBeep);
    //		motor[ClawLift] = 50;
    //		wait1Msec(200);
    //		motor[ClawLift] = 0;
    //		tmlatch = nPgmTime;
    //	}
    //}

    else if (joystick.joy2_Buttons & buttonLT)       // [Btn LT] turns conveyor belt on
		{
			servo[Belt] = 0;
		}
		else if (joystick.joy2_Buttons & buttonLS)       // [Btn LB] turns conveyor off
		{
			servo[Belt] = 127;
		}

	// Flapper/Kicker
		else if (joystick.joy2_Buttons & buttonB)                      //[Btn B] Kicks block into Conveyor
		{
					servoChangeRate[In]= 0;
					servo[In] = 125;
		}
		else if (joystick.joy2_Buttons & buttonX)                       //[Btn X] resets Flapper/Kicker into original position
		{
			servo[In] = 60 ;
		}

	//Release Blocks
		else if (joystick.joy2_Buttons & buttonA)      //[Btn A] resets Releaser to original position
		{
					servoChangeRate[Out]= 0;
		servo[Out] = 2 ;
		}
			else if (joystick.joy2_Buttons & buttonY)     //[Btn Y] opens the releaser to let block out
				//...This 'else if' statement makes [Btn A] a lower priority than [Btn Y]...
				//So if both buttons are pressed at the same time, you don't accidentally release the blocks.
		{
				servo[Out] = 100;
		}

		else
		{
			motor[ClawLift] = 0;
		}

		if (joystick.joy2_Buttons & buttonSTART)			// retract hook   [Btn start]
    {
      motor[Hook]= -90;
    }

    else if (joystick.joy2_Buttons & buttonBACK)	//give some hook       [Btn back]
    {
			motor[Hook]= 90;
    }

    else
		{
			motor[Hook] = 0;
		}
	}
}
