#pragma config(Hubs,  S3, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S3_C1_1,     mLeft,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     mRight,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C2_1,     nomotor,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_2,     Spinners,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C3_1,     PinPad,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C3_2,     Lifter,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C4_1,     Dumper,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C4_2,     fakemotor,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h";


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//																																																														//
//																								Autonomous Ramp Plan:																												//
//																																																														//
//	1.Set up Robot for competition.																																														//
//																																																														//
//	2.Drive down ramp using gyroscopic sensor and motor encoders.																															//
//																																																														//
//	3.Take IR reading to determine center goal position.																																			//
//																																																														//
//	4.Drive to 60cm rolling goal/Attach/Score using gyroscopic sensor and motor encoders.																			//
//																																																														//
//	5.Drive to Parking Zone using gyroscopic sensor and motor encoders.																												//
//																																																														//
//	6.Release 60 cm rolling goal in Parking Zone.																																							//
//																																																														//
//	7.Drive to and knock over Kickstand, using gyroscopic sensor and motor encoders based upon previous IR reading.						//
//																																																														//
//	8.Score in center roaling goal using gyroscopic sensor and motor encoders based upon previous IR reading.									//
//																																																														//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
		nMotorEncoder[mRight]=0;								//reset motor encoders
		nMotorEncoder[mLeft]=0;
	return;
}

void SetUp()
{
		// Drop Spinners, calibrate moving parts if needed
}

void Movement(float MR, float ML, float R, float L)
{
		nMotorEncoderTarget[mRight]=1440*MR;
		nMotorEncoderTarget[mLeft]=1440*ML;

		motor[mRight]=R;
		motor[mLeft]=L;

		nMotorEncoder[mRight]=0;								//reset motor encoders
		nMotorEncoder[mLeft]=0;

		motor[mRight]=0;
		motor[mLeft]=0;

	return;
}

task main()
{
	initializeRobot();

  tHTIRS2 irSeeker;
	initSensor(&irSeeker, IR);

	int CenterPosition = 0;

//	waitForStart();

		SetUp();

	Movement(-2.5,-2.5,-50,-50);		//Drive off ramp

  while (true)
  {
    readSensor(&irSeeker);
	  displayTextLine(1, "D:%4d", irSeeker.acDirection);

		if (irSeeker.acDirection == 5)
		{
		  playSound(soundBeepBeep);
		  displayTextLine(2, " IR is 5");
		  CenterPosition = 1;
		  wait1Msec(1000);
		}
		else if (irSeeker.acDirection == 7)								// 7 is a guess, might need changing
		{
			playSound(soundUpwardTones);
		  displayTextLine(2, " IR is 7");
			CenterPosition = 2;
			wait1Msec(1000);
	  }

	  else
	  {
	  	playSound(soundShortBlip);
	  	displayTextLine(2, " IR is 0");
			CenterPosition = 3;
			wait1Msec(1000);
	  }
  }


	Movement(-1.25,-1.25,-50,-50);		//Grab rolling goal

	//Drop PinPad

	Movement(-0.15,0.15,-50,50); 						//rotate towards ParkingZone
	Movement(5,5,50,50);						//Drive towards Parking Zone
	Movement(-0.35,0.35,-50,50);					//Rotate in place to put rolling goal in ParkingZone

	//Lift PinPad

	 switch(CenterPosition)
 {
  case 1:                // if 'CenterPosition' is '1':

// 	 	Movement(1,1,50,50);
//		Movement(0.5,-0.5,50,-50);						// Old untested Kickstand code.
//		Movement(1,1,50,50);

  	Movement(0.25,-0.25,50,-50);
  	Movement(2,2,50,50);
		Movement(-0.25,0.25,-50,50);
		Movement(1.5,1.5,50,50);
		Movement(0.25,-0.25,50,-50);
		Movement(-0.5,-0.5,-50,-50);

		//Drop Bucket

		Movement(0.5,0.5,50,50);
		Movement(-0.25,0.25,-50,50);
		Movement(0.5,0.5,50,50);
		Movement(-0.25,0.25,-50,50);
		Movement(2,2,50,50);

		break;                 					// break out of this switch statement and continue code after the '}'

  case 2:                						// if 'CenterPosition' is '2':

//		Movement(1,1,50,50);
//		Movement(1,-1,50,-50);				// Old untested Kickstand code.

  	Movement(0.25,-0.25,50,-50);
  	Movement(2,2,50,50);
		Movement(0.15,-0.15,50,-50);
		Movement(-1,-1,-50,-50);

		//Drop Bucket

		Movement(0.5,0.5,50,50);
		Movement(-0.25,0.25,-50,50);
		Movement(0.5,0.5,50,50);
		Movement(-0.25,0.25,-50,50);
		Movement(2,2,50,50);

  break;                 // break out of this switch statement and continue code after the '}'

  case 3:								 // if 'CenterPosition' is '3':

//  	Movement(2,2,50,50);					// Old untested Kickstand code.

    Movement(0.25,-0.25,50,-50);
  	Movement(0.5,0.5,50,50);
		Movement(0.25,-0.25,50,-50);
		Movement(-0.5,-0.5,-50,-50);

		//Drop Bucket

		Movement(0.5,0.5,50,50);
		Movement(-0.25,0.25,-50,50);
		Movement(0.5,0.5,50,50);
		Movement(-0.25,0.25,-50,50);
		Movement(2,2,50,50);

  break;								 // break out of this switch statement and continue code after the '}'

  default:               // if 'CenterPosition' is anything other than '1', '2', or '3'
		Movement(0,0,0,0);
 }
 playSound(soundFastUpwardTones);

}
