#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     IR,             sensorI2CCustom)
#pragma config(Motor,  mtr_S4_C1_1,     motorLF,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     motorRF,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorLB,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_2,     motorRB,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     Spinners,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     Lifter,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C4_1,    PinPad,               tServoStandard)
#pragma config(Servo,  srvo_S4_C4_2,    Dumper,               tServoStandard)
#pragma config(Servo,  srvo_S4_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h";


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//																																																														//
//																								Autonomous Ramp Plan:																												//
//																																																														//
//	1.Set up Robot for competition.																																														//
//																																																														//
//	2.Drive down ramp using gyroscopic sensor and motor encoders.																															//
//																																																														//
//	3.Take IR reading to determine center goal position.																																			//
//																																																														//
//	4.Drive to 60cm rolling goal/Attach/Score using gyroscopic sensor and motor encoders.																			//
//																																																														//
//	5.Drive to Parking Zone using gyroscopic sensor and motor encoders.																												//
//																																																														//
//	6.Release 60 cm rolling goal in Parking Zone.																																							//
//																																																														//
//	7.Drive to and knock over Kickstand, using gyroscopic sensor and motor encoders based upon previous IR reading.						//
//																																																														//
//	8.Score in center roaling goal using gyroscopic sensor and motor encoders based upon previous IR reading.									//
//																																																														//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{

		nMotorEncoder[motorRF] = 0;
		nMotorEncoder[motorRB] = 0;
		nMotorEncoder[motorLF] = 0;
		nMotorEncoder[motorLB] = 0;
}

void SetUp()
{
		// Drop Spinners, calibrate moving parts if needed
	return;
}

void Movement(float MR, float ML, float R, float L)
{
		nMotorEncoderTarget[motorRF]=1440*MR;
		nMotorEncoderTarget[motorRB]=1440*MR;
		nMotorEncoderTarget[motorLF]=1440*ML;
		nMotorEncoderTarget[motorLB]=1440*ML;


		motor[motorRF] = (R);
		motor[motorRB] = (R);
		motor[motorLF] = (L);
		motor[motorLB] = (L);

		nMotorEncoder[motorRF]=1440*MR;
		nMotorEncoder[motorRB]=1440*MR;
		nMotorEncoder[motorLF]=1440*ML;
		nMotorEncoder[motorLB]=1440*ML;

		motor[motorRF] = 0;
		motor[motorRB] = 0;
		motor[motorLF] = 0;
		motor[motorLB] = 0;

		nMotorEncoderTarget[motorRF]=0;
		nMotorEncoderTarget[motorRB]=0;
		nMotorEncoderTarget[motorLF]=0;
		nMotorEncoderTarget[motorLB]=0;

	return;
}

task main()
{

	initializeRobot();

  tHTIRS2 irSeeker;
	initSensor(&irSeeker, S1);

	int CenterPosition = 0;

//	waitForStart();

		SetUp();

	Movement(-3.25,-3.25,-50,-50);		//Drive off ramp

  wait1Msec(250);

    readSensor(&irSeeker);
	  displayTextLine(1, "D:%4d", irSeeker.acDirection);

		if (irSeeker.acDirection == 4)
		{
		  displayTextLine(2, " CF = 1");
		  CenterPosition = 1;
		  wait1Msec(150);
		}

		else if (irSeeker.acDirection == 5)
		{
		  displayTextLine(2, " CF = 2");
			CenterPosition = 2;
			wait1Msec(150);
	  }

	  else if (irSeeker.acDirection == 6)
	  {
	  	displayTextLine(2, " CF = 3");
			CenterPosition = 3;
			wait1Msec(150);
	  }

	  else {
	  	displayTextLine(2, "IR failure!");
	  	playSound(soundException);
	  	CenterPosition = 0;
	  	wait1Msec(150);
	  }

	//Drop PinPad

	  Movement(-0.15,0.15,-50,50);
	  Movement(5,5,50,50);
	  Movement(0.35,0.35,50,50);

	  if(CenterPosition == 0){
	  	//Drop Bucket
	}

		else{
		wait1Msec(50);
	}

  //Raise PinPad

	 switch(CenterPosition)
 {
  case 1:                // if 'CenterPosition' is '1':

  	Movement(0.25,-0.25,50,-50);
  	Movement(2,2,50,50);
		Movement(-0.25,0.25,-50,50);
		Movement(1.5,1.5,50,50);
		Movement(0.25,-0.25,50,-50);
		Movement(-0.5,-0.5,-50,-50);

		//Drop Bucket

		Movement(0.5,0.5,50,50);
		Movement(0.25,-0.25,50,-50);
		Movement(0.5,0.5,50,50);
		Movement(-0.25,0.25,-50,50);
		Movement(-2,-2,-50,-50);

		break;                 					// break out of this switch statement and continue code after the '}'

  case 2:                						// if 'CenterPosition' is '2':

			Movement(0.25,-0.25,50,-50);
			Movement(2,2,50,50);
			Movement(0.15,-0.15,50,-50);
			Movement(-0.5,-0.5,-50,-50);

		//Drop Bucket

		Movement(0.5,0.5,50,50);
		Movement(0.25,-0.25,50,-50);
		Movement(0.5,0.5,50,50);
		Movement(-0.25,0.25,-50,50);
		Movement(-2,-2,-50,-50);

  break;                 // break out of this switch statement and continue code after the '}'

  case 3:								 // if 'CenterPosition' is '3':

    Movement(0.25,-0.25,50,-50);
  	Movement(0.5,0.5,50,50);
  	Movement(0.25,-0.25,50,-50);
		Movement(-0.5,-0.5,-50,-50);

		//Drop Bucket

		Movement(0.5,0.5,50,50);
		Movement(0.25,-0.25,50,-50);
		Movement(0.5,0.5,50,50);
		Movement(-0.25,0.25,-50,50);
		Movement(-2,-2,-50,-50);

  break;								 // break out of this switch statement and continue code after the '}'

		  default:               // if IR misread, then do not move
		Movement(0,0,0,0);

		break;

 }
 playSound(soundFastUpwardTones);


}
