#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     mRight,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     mLeft,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Autonomous Parking Zone Plan:

1. Set up Robot for competition.

2. Drive towards opposing alliance's Ramp Zone using gyroscopic sensor and motor encoders.
		b. Drive close enough to not enter Ramp Zone, but far enough to not hit the kickstand.

3. Take IR reading to determine center field structure position, and score in center goal.

4. Drive towards opposing alliance's Parking Zone using gyroscopic sensor and motor encoders.
		b. Drive close enough to not enter Parking Zone, but far enough to not hit the kickstand.

5. Drive to 30cm rolling goal using gyroscopic sensor and motor encoders/Attach/Score.

6. Drive to Parking Zone using gyroscopic sensor and moter encoders.

7. Release 30cm rolling goal in Parking Zone.

8. Drive to/Kick Kickstand using gyroscopic sensor and motor encoders, based upon previous IR reading.
*/



void initializeRobot()
{
		nMotorEncoder[mRight]=0;								//reset motor encoders
		nMotorEncoder[mLeft]=0;
	return;
}

void Movement(int MR, int ML, int R, int L)
{
		nMotorEncoderTarget[mRight]=1440*MR;
		nMotorEncoderTarget[mLeft]=1440*ML;

		motor[mRight]=R;
		motor[mLeft]=L;

		nMotorEncoder[mRight]=0;								//reset motor encoders
		nMotorEncoder[mLeft]=0;

	return;
}

task main()
{
	initializeRobot();


//	waitForStart();

	Movement(3,3,50,50);
// IR CODE HERE
	Movement(1,1,50,50);




}
