#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     leftMotor,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     rightMotor,    tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//////////////////////////////////////////////////////////////////////////////////////

// LOG SCALE

//////////////////////////////////////////////////////////////////////////////////////

int scaleLog (int joySettings){
	int scaled = joySettings;

		int logScale [33] = {
			0, 0, 0, 5, 7, 10,
			13, 15, 17, 19, 20, 23,
			25, 27, 29, 31, 33, 37,
			40,  43, 45, 47, 50, 53,
			55, 57, 60, 65, 70, 75, 80,
			90, 99
		};

		if (true){
			scaled /= 4;

			if (scaled <= 0){
				scaled = -logScale [-scaled];
			}
		}

		wait1Msec (5);
		return scaled;
}


////////////////////////////////////////////////////////////////////////////

// MAIN

////////////////////////////////////////////////////////////////////////////


task main()
{
	motor [leftMotor] = 0;
	motor [rightMotor] = 0;
  wait1Msec (5);

	while(true){
		getJoystickSettings (joystick);

		int yValue = joystick.joy1_y2;
		yValue = scaleLog (yValue);

		int xValue = joystick.joy1_x1;
		xValue = scaleLog (xValue);


		if (yValue != 0){
			xValue /= 2;

			if (yValue < 0){

				if (xValue < 0){
					motor [leftMotor] = yValue + xValue;
					motor [rightMotor] = yValue;
				}
				else{
					motor [leftMotor] = yValue;
					motor [rightMotor] = yValue + xValue;
				}
			}
			else{
				if (xValue < 0){
					motor [leftMotor] = yValue - xValue;
					motor [rightMotor] = yValue;
				}
				else{
					motor [leftMotor] = yValue;
					motor [rightMotor] = yValue - xValue;
				}
			}
		}
		wait1Msec (5);
	}
}
