#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     Stopper,        sensorTouch)
#pragma config(Sensor, S3,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S2_C1_1,     motorRF,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     Spinners,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     motorLB,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     motorRB,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C3_1,     Lifter,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C3_2,     motorLF,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S4_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_2,    PinPad,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    Dumper,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//////////////////////////////////////////////////////////////////////////////////////

// LOG SCALE

//////////////////////////////////////////////////////////////////////////////////////

	static const int logScale[33] =
	{
		0,   0,   0,	 0,		0,
		1,	 2,   4,   5,		7,
		9,  11,  13,  15,	 18,
		21,  24,	 27,  31,	 34,
		38,	42,	 46,	51,	 55,
		60,	65,	 70,	75,	 81,
		87,	95,	 99,

	};

int scaleLog (int joySettings){
	int scaled = joySettings;
/*
		int logScale [33] = {
			0, 0, 0, 5, 7, 10,
			13, 15, 17, 19, 20, 23,
			25, 27, 29, 31, 33, 37,
			40,  43, 45, 47, 50, 53,
			55, 57, 60, 65, 70, 75, 80,
			90, 99
		};
*/
		if (true){
			scaled /= 4;

			if (scaled <= 0){
				scaled = -logScale [-scaled];
			}
			else{
				scaled = logScale [scaled];
			}
		}

		wait1Msec (5);
		return scaled;
}


////////////////////////////////////////////////////////////////////////////

// MAIN

////////////////////////////////////////////////////////////////////////////


task main()
{
	while(true){
		getJoystickSettings (joystick);

		int yValue = joystick.joy1_y2;
		yValue = scaleLog (yValue);

		int xValue = joystick.joy1_x1;
		xValue = scaleLog (xValue);

		int FR = yValue;
		int rotation = xValue*3/4;

		motor [motorRF] = FR - rotation;
		motor [motorRB] = FR - rotation;
		motor [motorLF] = FR + rotation;
		motor [motorLB] = FR + rotation;


	}		//While
}			//Task

/*

		if (yValue != 0){
			xValue /= 2;

			if (yValue < 0){

				if (xValue < 0){																	//Right Backwards Turn
					motor [leftMotor] = yValue + xValue;
					motor [rightMotor] = yValue;
				}
				else{
					motor [leftMotor] = yValue;											//Left Backwards Turn
					motor [rightMotor] = yValue + xValue;
				}
			}
			else{
				if (xValue < 0){																	//
					motor [leftMotor] = yValue - xValue;
					motor [rightMotor] = yValue;
				}
				else{
					motor [leftMotor] = yValue;
					motor [rightMotor] = yValue - xValue;
				}
			}
		}
		wait1Msec (5);
	}
}

*/
