#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     Stopper,        sensorTouch)
#pragma config(Sensor, S3,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S2_C1_1,     motorRF,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     Spinners,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     motorLB,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     motorRB,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C3_1,     Lifter,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C3_2,     motorLF,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S4_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_2,    PinPad,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    Dumper,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h";											//Include file that allows our IR seeker to work properly

#define buttonX   	0x01   		//[Btn X]
#define buttonA   	0x02	  	//[Btn A]
#define buttonB   	0x04   		//[Btn B]
#define buttonY   	0x08   		//[Btn Y]
#define buttonLS   	0x10   		//[Btn Left Shoulder]
#define buttonRS   	0x20   		//[Btn Right Shoulder]
#define buttonLT   	0x40   		//[Btn Left Trigger]
#define buttonRT   	0x80   		//[Btn Right Trigger]
#define buttonBACK  0x100			//[Btn Back]
#define buttonSTART 0x200			//[Btn Start]

const bool bLogarithmicScale = true;
const float kMaximumPowerLevel = 100;  // Adjust to set max power level to be used.

int scaleLog(int &nJoy1,int nMaxValue = kMaximumPowerLevel)

{
	// This function scales the joystick settings to the appropriate range for
	// controlling a NXT motor.
	//
	// Joystick values range from -128 to +127.
	// Speed/power settings for NXT motors range from -100 to +100
	//
	// The physical range of motion of a joystick is quite small and it is sometimes
	// hard to control slow speeds. So another capability of this program to apply
	// a "logarithmic" scale to the joystick settings. Our scale is not exactly a logarithmic.
	// it runs smaller numbers untill about half speed then increases quickly.
	static const int nLogScale[33] =
	{
		0,   0,   0,	 0,		0,
		1,	 2,   4,   5,		7,
		9,  11,  13,  15,	 18,
		21,  24,	 27,  31,	 34,
		38,	42,	 46,	51,	 55,
		60,	65,	 70,	75,	 81,
		87,	95,	 99,

	};

	int nScaled;

	nScaled = nJoy1;
	if (bLogarithmicScale)
	{
		nScaled /= 4;
		if (nScaled >= 0)
			nScaled = nLogScale[nScaled];
		else
			nScaled = - nLogScale[ - nScaled];
	}
	nScaled *= nMaxValue;
	nScaled /= 100;

	return nScaled;
}

void TankDrive(int L, int R)
{
	motor[motorRF] = scaleLog(R);
	motor[motorRB] = scaleLog(R);
	motor[motorLF] = scaleLog(L);
	motor[motorLB] = scaleLog(L);

	return;
}

//This function will be used to run presets for the lift. It is not yet tested or operational.

/*
void Lift(float x)
{

	if(x == 0)
	{
		while(SensorValue[Stopper] == 0){
			motor[Lifter] = -75;
		}
		return;
	}

	else{

		nMotorEncoderTarget[Lifter] = 1440*x;

		motor[Lifter] = 75;

		while(nMotorRunState[Lifter] != runStateIdle){													// while our motors are not idle run this code

			writeDebugStreamLine("Motor Encoder = %d", nMotorEncoder[Lifter]);
		}

		motor[Lifter]= 0;

	return;
	}
}
*/

int Toggle = 0;
int x = 165;
int y = 255;

task main()
{

	nMotorEncoder[Lifter] = 0;

//		servoMaxPos[PinPad] = 125;
//		servoMinPos[PinPad] = 10;
		servoChangeRate[PinPad] = 5;

//		servoMaxPos[Dumper] = 125;
//		servoMinPos[Dumper] = 10;
		servoChangeRate[Dumper] = 2;


	while (true)
	{
		getJoystickSettings(joystick);  // The joystick global is defined in joystick.c

		TankDrive(joystick.joy1_y1, joystick.joy1_y2);

//////////////////////////////////////////////////////////////////////
// Begining of driver One																						//
//////////////////////////////////////////////////////////////////////

				if (joystick.joy1_Buttons & buttonLT)
					{
						Toggle = 1;
						wait1Msec(100);
					}
				else if (joystick.joy1_Buttons & buttonRT)
					{
						Toggle = 2;
						wait1Msec(100);
					}

				else if (joystick.joy1_Buttons & buttonSTART)
					{
						Toggle = 0;
						wait1Msec(100);
					}

				else if (joystick.joy1_Buttons & buttonA)
					{
						x++;
						servo[PinPad] = x;
						wait1Msec(15);
					}

				else if (joystick.joy1_Buttons & buttonY)
					{
						x--;
						servo[PinPad] = x;
						wait1Msec(15);
					}

				else
					{

						if(Toggle == 0)
							{
								motor[Spinners] = 0;
							}

						else if(Toggle == 1)
							{
								motor[Spinners] = 75;
							}

						else if(Toggle == 2)
							{
								motor[Spinners] = -75;
							}
					}

//////////////////////////////////////////////////////////////////////
// Begining of driver Two																						//
//////////////////////////////////////////////////////////////////////

				if (joystick.joy2_Buttons & buttonRS)
					{
						motor[Lifter] = 50;
					}

				else if (joystick.joy2_Buttons & buttonRT)
					{
						if (SensorValue(Stopper) == 1)
							{
								motor[Lifter] = 0;
							}

						else
							{
								motor[Lifter] = -50;
							}
					}
/*
				else if (joystick.joy2_Buttons & buttonA)
					{
						Lift(2);
					}

				else if (joystick.joy2_Buttons & buttonX)
					{
						Lift(4);
					}

				else if (joystick.joy2_Buttons & buttonY)
					{
						Lift(6);
					}

				else if (joystick.joy2_Buttons & buttonB)
					{
						Lift(8);
					}

				else if (joystick.joy2_Buttons & buttonSTART)
					{
						Lift(0);
					}

*/

				else if (joystick.joy2_Buttons & buttonY)
					{
						y++;
						servo[Dumper] = y;
						wait1Msec(10);
					}

				else if (joystick.joy2_Buttons & buttonA)
					{
						y--;
						servo[Dumper] = y;
						wait1Msec(10);
					}

				else if (joystick.joy2_Buttons & buttonLS)
					{
						y = 240;
						servo[Dumper] = 240;
						wait1Msec(15);
					}

				else if (joystick.joy2_Buttons & buttonLT)
					{
						y = 125;
						servo[Dumper] = 125;
						wait1Msec(15);
					}

				else
					{
						motor[Lifter] = 0;

						writeDebugStreamLine("Stopper = %d", ServoValue[Dumper]);

					}
	}
}
