#pragma config(Hubs,  S3, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S3_C1_1,     mLeft,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     mRight,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_2,     Spinners,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C3_1,     PinPad,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C3_2,     Lifter,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C4_1,     Dumper,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C4_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define buttonX   	0x01   		//[Btn X]
#define buttonA   	0x02	  	//[Btn A]
#define buttonB   	0x04   		//[Btn B]
#define buttonY   	0x08   		//[Btn Y]
#define buttonLS   	0x10   		//[Btn LB]
#define buttonRS   	0x20   		//[Btn RB]
#define buttonLT   	0x40   		//[Btn LT]
#define buttonRT   	0x80   		//[Btn RT]
#define buttonBACK  0x100			//[Btn Back]
#define buttonSTART 0x200			//[Btn Start]

const bool bLogarithmicScale = true;
const float kMaximumPowerLevel = 100;  // Adjust to set max power level to be used.

int scaleLog(int &nJoy1,int nMaxValue = kMaximumPowerLevel)

{
	// This function scales the joystick settings to the appropriate range for
	// controlling a NXT motor.
	//
	// Joystick values range from -128 to +127.
	// Speed/power settings for NXT motors range from -100 to +100
	//
	// The physical range of motion of a joystick is quite small and it is sometimes
	// hard to control slow speeds. So another capability of this program to apply
	// a "logarithmic" scale to the joystick settings. Our scale is not exactly a logarithmic.
	// it runs smaller numbers untill about half speed then increases quickly.
	static const int nLogScale[33] =
	{
		0,   0,   0,	 0,		0,
		1,	 2,   4,   5,		7,
		9,  11,  13,  15,	 18,
		21,  24,	 27,  31,	 34,
		38,	42,	 46,	51,	 55,
		60,	65,	 70,	75,	 81,
		87,	93,	 99,

	};

	int nScaled;

	nScaled = nJoy1;
	if (bLogarithmicScale)
	{
		nScaled /= 4;
		if (nScaled >= 0)
			nScaled = nLogScale[nScaled];
		else
			nScaled = - nLogScale[ - nScaled];
	}
	nScaled *= nMaxValue;
	nScaled /= 100;
	return nScaled;
}

void TankDrive(int L, int R)
{
	motor[mRight] = scaleLog(R);
	motor[mLeft] = scaleLog(L);
	return;
}

void initializeRobot()
{
	return;
}

task main()
{
	initializeRobot();

	while (true)
	{
		getJoystickSettings(joystick);  // The joystick global is defined in joystick.c

		TankDrive(joystick.joy1_y1, joystick.joy1_y2);

//////////////////////////////////////////////////////////////////////
// Begining of driver One																						//
//////////////////////////////////////////////////////////////////////

				if (joystick.joy1_Buttons & buttonRS) {
			motor(Spinners) = 50;
	}

				else if (joystick.joy1_Buttons & buttonLS) {
			motor(Spinners) = -50;
	}

				else {
			motor(Spinners) = 0;
		}

//////////////////////////////////////////////////////////////////////
// Begining of driver Two																						//
//////////////////////////////////////////////////////////////////////

		//////////////////////////////////////////////////////////////////////
		// All Code is written for motors, might need change								//
		//////////////////////////////////////////////////////////////////////

				if (joystick.joy2_Buttons & buttonRS) {
			motor(Lifter) = 50;
	}

				else if (joystick.joy2_Buttons & buttonRT) {
			motor(Lifter) = -50;
	}

				else if (joystick.joy2_Buttons & buttonLS) {
			motor(Dumper) = 15;
	}

				else if (joystick.joy2_Buttons & buttonLT) {
			motor(Dumper) = -15;
	}

				else if (joystick.joy2_Buttons & buttonA) {
			motor(PinPad) = 15;
	}

				else if (joystick.joy2_Buttons & buttonY) {
			motor(PinPad) = -15;
	}

		else {
			motor(Lifter) = 0;
			motor(Dumper) = 0;
			motor(PinPad) = 0;
		}

	}
}
