#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     motorLB,       tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     motorRB,       tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S4_C2_1,     Lifter,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S4_C2_2,     Spinners,       tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S4_C3_1,    Dumper,               tServoStandard)
#pragma config(Servo,  srvo_S4_C3_2,    PinPad,               tServoStandard)
#pragma config(Servo,  srvo_S4_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define buttonX   	0x01   		//[Btn X]
#define buttonA   	0x02	  	//[Btn A]
#define buttonB   	0x04   		//[Btn B]
#define buttonY   	0x08   		//[Btn Y]
#define buttonLS   	0x10   		//[Btn Left Shoulder]
#define buttonRS   	0x20   		//[Btn Right Shoulder]
#define buttonLT   	0x40   		//[Btn Left Trigger]
#define buttonRT   	0x80   		//[Btn Right Trigger]
#define buttonBACK  0x100			//[Btn Back]
#define buttonSTART 0x200			//[Btn Start]

const bool bLogarithmicScale = true;
const float kMaximumPowerLevel = 100;  // Adjust to set max power level to be used.

int scaleLog(int &nJoy1,int nMaxValue = kMaximumPowerLevel)

{
	// This function scales the joystick settings to the appropriate range for
	// controlling a NXT motor.
	//
	// Joystick values range from -128 to +127.
	// Speed/power settings for NXT motors range from -100 to +100
	//
	// The physical range of motion of a joystick is quite small and it is sometimes
	// hard to control slow speeds. So another capability of this program to apply
	// a "logarithmic" scale to the joystick settings. Our scale is not exactly a logarithmic.
	// it runs smaller numbers untill about half speed then increases quickly.
	static const int nLogScale[33] =
	{
		0,   0,   0,	 0,		0,
		1,	 2,   4,   5,		7,
		9,  11,  13,  15,	 18,
		21,  24,	 27,  31,	 34,
		38,	42,	 46,	51,	 55,
		60,	65,	 70,	75,	 81,
		87,	93,	 99,

	};

	int nScaled;

	nScaled = nJoy1;
	if (bLogarithmicScale)
	{
		nScaled /= 4;
		if (nScaled >= 0)
			nScaled = nLogScale[nScaled];
		else
			nScaled = - nLogScale[ - nScaled];
	}
	nScaled *= nMaxValue;
	nScaled /= 100;
	return nScaled;
}

void TankDrive(int L, int R)
{
//	motor[motorRF] = scaleLog(R);
	motor[motorRB] = scaleLog(R);
//	motor[motorLF] = scaleLog(L);
	motor[motorLB] = scaleLog(L);
	return;
}


task main()
{

	while (true)
	{
		getJoystickSettings(joystick);  // The joystick global is defined in joystick.c

		TankDrive(joystick.joy1_y1, joystick.joy1_y2);

//		servoMaxPos[PinPad] = 125;
//		servoMinPos[PinPad] = 10;
		servoChangeRate[PinPad] = 5;

//		servoMaxPos[Dumper] = 125;
//		servoMinPos[Dumper] = 10;
		servoChangeRate[Dumper] = 1;

//////////////////////////////////////////////////////////////////////
// Begining of driver One																						//
//////////////////////////////////////////////////////////////////////

				if (joystick.joy1_Buttons & buttonRT) {
			motor(Spinners) = 15;
	}
				else if (joystick.joy1_Buttons & buttonLT) {
			motor(Spinners) = -15;
	}
//				else if (joystick.joy1_Buttons & buttonX) {
//			servo(PinPad) += 1;
//	}

//				else if (joystick.joy1_Buttons & buttonB) {
//			servo(PinPad) -= 1;
//	}

					else if (joystick.joy1_Buttons & buttonA) {
			servo(PinPad) = 250;
	}

				else if (joystick.joy1_Buttons & buttonY) {
			servo(PinPad) = 155;
	}

				else {
			motor(Spinners) = 0;
		}

//////////////////////////////////////////////////////////////////////
// Begining of driver Two																						//
//////////////////////////////////////////////////////////////////////

				if (joystick.joy2_Buttons & buttonRS) {
			motor(Lifter) = 50;
	}

				else if (joystick.joy2_Buttons & buttonRT) {
			motor(Lifter) = -50;
	}
//				else if (joystick.joy2_Buttons & buttonX) {
//			servo(Dumper) += 1;
//	}

//				else if (joystick.joy2_Buttons & buttonB) {
//			servo(Dumper) -= 1;
//	}
				else if (joystick.joy2_Buttons & buttonLS) {
			servo(Dumper) = 15;
	}

				else if (joystick.joy2_Buttons & buttonLT) {
			servo(Dumper) = 50;
	}

		else {
			motor(Lifter) = 0;
		}

	}
}
